Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
#src	= Glob('*.c')
src = Split("""
board.c
stm32f4xx_it.c
drv_usart.c
platform.c
stm32f4xx_hal_msp.c
""")

CPPPATH = [cwd]
if GetDepend('RT_USING_SPI'):
	src = src + ['drv_stm32f40x_spi.c']
#if GetDepend('RT_USING_SPI_MSD'):
#    src += ['drv_spi_msd.c']
if GetDepend('RT_USING_SPI_LCD'):
	src = src + ['drv_lcd_st7735.c','drv_spi_lcd.c']

	
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

